CREATE TABLE `my_db`.`users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Age` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `user_id_UNIQUE` (`ID` ASC) VISIBLE);